### ISSUE TITLE
JUNIT:  can't test single method after testing whole Class

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.debug#135]
For example:
1. run all Tests in the class: FileStoreTest -> "Run As" / "Junit Plugin-Test"  
2. try to run a single method: FileStoreTest.testCopyFile -> "Run As" / "FileStoreTest". Run As "Junit Plugin-Test" is missing now.

Did work in previous eclipse versions.

@mickaelistria @laeubi 
regression from https://github.com/eclipse-platform/eclipse.platform.debug/pull/122

Workaround: delete "FileStoreTest" launch config before launching FileStoreTest.testCopyFile.

Suggestion: There should always be the old option to "Run As" / "Junit Plugin-Test" too.

**Comment by laeubi** [comment]
> and also show expanded launch configurations only if there are multiple ones (in case there is only 1, multiplying entries doesn't seem so valuable, and the only benefit is to show the launch config name early, which is relatively minor compared to over-crowding the menu)

I think it would be good if the shortcut can somehow indicate the desired behavior, because this is of course a valid choice and it does not necessarily duplicate things, because a `LaunchShortcut` can do anything, it must not created a launch config at all. So assuming that a _launch shortcut_ is always the same as a _launch config_ and will always launch that config if there is one might be often the case but is not a requirement (as you see here).

Maybe it should also be checked the implementation of the shortcut, it seems to not compute the right value then here according to the selection.
